# Generated by Django 4.0.2 on 2022-04-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='students_name',
        ),
        migrations.AddField(
            model_name='user',
            name='teachers_name',
            field=models.CharField(default='Empty', max_length=100),
            preserve_default=False,
        ),
    ]
